'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('ticks', [
      {
        "id": 1,
        "scientific": "Ixodes scapularis",
        "common": "Blacklegged Tick, Deer Tick",
        "intro": "The Blacklegged ticks are known for potentially carrying Lyme Disease, an inflammatory disease caused by a bacterial infection from an infected tick bite. Black-legged tick nymphs and adults tick can bite people, so it's essential to recognize if a tick is on you.",
        "colors": "Reddish and black or brown",
        "shape": "Oval or sesame seed-like",
        "hosts": "Primary hosts include mice, chipmunks, white-tailed deer, and people.",
        "habitat": "Leaf litter or dead and fallen plant material, including shrubby and wooded areas.",
        "njLocations": "Common locations are in rural and suburban areas. The first report of Ixodes scapularis in New Jersey was in Mercer County. It's understood that this tick is distributed statewide and is very common to come across.",
        "larvaeActive": "Active between April to November",
        "larvaeFeed": "larvae primarily feed on small mammals, such as mice and birds.",
        "nymphActive": "Active between April to July, October, November",
        "nymphFeed": "nymphs primarily feed on small to large mammals ranging from deer to people.",
        "adultActive": "Active between October to June months while above freezing temperatures",
        "adultFeed": "adults primarily feed on large mammals, including people.",
        "featureImgUrl": "http://localhost:3003/public/siteImages/scapularis.jpg",
        "mapImgUrl": "https://www.cdc.gov/ticks/images/geo/lgmap-american_dog_tick.jpg",
        "refImgArray": "[{source: 'https://digitalcommons.georgiasouthern.edu/usntc_key/1089/thumbnail.jpg', caption: 'Author: Say; Male Ixodes scapularis from Georgia Southern University RML Number 119928 '},]",
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 2,
        "scientific": "Amblyomma americanum",
        "common": "Lone Star Tick",
        "intro": "Lone star ticks are three-host ticks, where the larval, nymphal, and adult stages can feed on people, domesticated animals, ground-dwelling birds, small and large wild mammals.",
        "colors": null,
        "shape": "rounder in shape than other tick species",
        "hosts": null,
        "habitat": "Very dry, forested areas, scrubby areas, or along the Atlantic coast",
        "njLocations": "Primarily in southern parts of the state but may be expanding north",
        "larvaeActive": "Jul to Sep",
        "larvaeFeed": "birds and mammals excluding small rodents, and people",
        "nymphActive": "Mar to Oct",
        "nymphFeed": "birds and mammals excluding small rodents, and people",
        "adultActive": "Apr to Aug",
        "adultFeed": "large/medium-sized mammals, but can be found on small rodents, wild turkeys, and people.",
        "featureImgUrl": "http://localhost:3003/public/siteImages/americanum.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 3,
        "scientific": "Amblyomma maculatum",
        "common": "Gulf Coast Tick",
        "intro": "Formerly distributed in Southeastern U.S. but new populations are being reported in Delaware and Maryland.  The closest distribution was in Delaware's Bombay Hook National Wildlife Refuge which is less than 13 miles from the Delware Bay in New Jersey.  Salem, Cumberland, and Cape May Counties border the Delaware Bay.",
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "open grassy areas and pastures",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/maculatum.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 4,
        "scientific": "Carios kelleyi",
        "common": null,
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "Where bats roost, which may be places like older homes, barns or cabins.  Other environments include grasslands or vegetation along forest edges.",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/kelleyi.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 5,
        "scientific": "Dermacenter albipictus",
        "common": "Moose Tick",
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "forested areas",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/albipictus.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 6,
        "scientific": "Dermacenter variabilis",
        "common": "American Dog Tick, Wood Tick",
        "intro": "The American Dog Tick, also known as the Wood Tick is commonly found in overgrown fields rather than in wooded, forestry areas. Pasteurizing cattle and horses are found to host these ticks, along with other types of mammals that roam fields including white-footed mice, meadow voles, and rats.",
        "colors": null,
        "shape": "oblong",
        "hosts": null,
        "habitat": "Tree-line edges with barely any tree coverage, grassy fields, or where vegetation is not maintained",
        "njLocations": "Rural and suburban areas, and was known to be found in vacant lots and rights-of-ways",
        "larvaeActive": "May to Sep",
        "larvaeFeed": "small wild mammals",
        "nymphActive": "Apr to Jul",
        "nymphFeed": "small wild mammals",
        "adultActive": "Mar to Aug",
        "adultFeed": "large mammals such as wild mammals, cattle, pets, and people",
        "featureImgUrl": "http://localhost:3003/public/siteImages/variabilis.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 7,
        "scientific": "Haemaphysalis leporispalustris",
        "common": "Rabbit Tick",
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "forests with pines, shrubs, or mixed vegetation",
        "njLocations": "Understood to be widely distributed across the eastern United States",
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/leporispalustris.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 8,
        "scientific": "Haemaphysalis longicornis",
        "common": "Asian Longhorned Tick, Bush Tick",
        "intro": "The Asian longhorned tick parasitizes and spreads quickly, commonly found among cattle and other farm animals in large numbers, but can feed on birds, pets, and humans. In 2017, the Longhorned Tick was first reported in the U.S. in New Jersey.",
        "colors": null,
        "shape": "tear-drop/sesame seed-like shape",
        "hosts": null,
        "habitat": "Tall grasses, meadows, and pastures. Commonly found on farms.",
        "njLocations": "Hunterdon, Union, Middlesex, Mercer, Bergen, Somerset, Passaic, Camden, and Monmouth",
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": "animals dependent on temperature, humidity, and host availability",
        "featureImgUrl": "http://localhost:3003/public/siteImages/longicornis.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 9,
        "scientific": "Ixodes brunneus",
        "common": null,
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "grasslands, woodlands, scrubs. Due to the migratory patterns of passerines, can be found in diverse environments",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/brunneus.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 10,
        "scientific": "Ixodes cookei",
        "common": null,
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "fields, forests, hedgerows, and pastures",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/cookei.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 11,
        "scientific": "Ixodes dentatus",
        "common": null,
        "intro": "In later years, was identified in Bergen and Union counties.  This tick is usually distributed along the Atlantic Coast",
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "grasslands, bushy woodlands, and croplands",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/dentatus.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 12,
        "scientific": "Ixodes texanus",
        "common": null,
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "moist woodland areas, farmlands, suburban, and urban areas",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/texanus.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      },
      {
        "id": 13,
        "scientific": "Rhipicephalus sanguineus",
        "common": null,
        "intro": null,
        "colors": null,
        "shape": null,
        "hosts": null,
        "habitat": "Outdoor environments near walls or gardens, adapted to homes in rural and urban areas",
        "njLocations": null,
        "larvaeActive": null,
        "larvaeFeed": null,
        "nymphActive": null,
        "nymphFeed": null,
        "adultActive": null,
        "adultFeed": null,
        "featureImgUrl": "http://localhost:3003/public/siteImages/sanguineus.jpg",
        "mapImgUrl": null,
        "createdAt": "2022-04-20 13:17:24",
        "updatedAt": "2022-04-20 13:17:24"
      }
    ], {});
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('ticks', null, {});
  }
};
