'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('ticks', [
      {
          id: 1,
          common: "blacklegged tick (old name “deer tick)",
          scientific: "Ixodes scapularis",
          humanHosts: 1,
          intro: "Blacklegged ticks are the only ticks known to transmit (i.e. vector) Lyme Disease, an inflammatory disease caused by a spirochete bacteria, Borrelia burgdorferi, in New Jersey. They can also transmit Anaplasmosis, Babesiosis, Borrelia miyamotoi disease, and Powassan virus. All stages of the blacklegged tick feed on people, however nymphs and adults are most likely to transmit pathogens, and nymphs are especially dangerous because their small size makes them harder to detect. Practicing tick prevention while enjoying nature is essential to minimize your risk of contracting a tick-borne disease.",
          hosts: "Blacklegged ticks are found on various hosts such as field mice, chipmunks, skunks, raccoons, white-tailed deer, dogs, and people.",
          habitat: "Wooded areas in New Jersey include forest edges along paths or trails. This tick is very sensitive to drying and is active mostly in shaded areas and early in the morning and late in the evening.",
          njLocations: "This tick species is distributed statewide and is relatively common. However, in the 1940s, blacklegged ticks were not listed in New Jersey. As recently as the early 1980s, this tick species was restricted to southern New Jersey, especially the coastal plains.",
          activeMonths: "Tick Larvae\nActive from April to November, peak abundance occurs from August to October. Larvae feed primarily on small mammals, such as field mice and birds, which are pathogen reservoirs.\n\nTick Nymph\nActive from April to November, peak abundance occurs from May to July. Nymphs feed on small to large mammals ranging from mice to deer and people.\n\nTick Adult \nActive from October to April, peak abundance in Fall and Spring but can be found throughout Winter when temperatures are above freezing. Adult blacklegged ticks feed primarily on large mammals, including deer and people. ",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1089/thumbnail.jpg",
          featureImgUrl: "/images/i–scap_egizi.png",
          mapImgUrl: "",
          refImgArray: "{\"images\": [\"/images/i–scap_egizi.png\", \"/images/AAAA.jpeg\", \"/images/AAA.jpeg\", \"/images/scap3.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 2,
          common: "lone star tick",
          scientific: "Amblyomma americanum",
          humanHosts: 1,
          intro: "Lone star ticks are aggressive biters, can be abundant, and carry the bacterial pathogens responsible for Ehrlichiosis, an increasingly common disease in New Jersey. Check out our page on tick-borne diseases to learn more!",
          hosts: "Lone star ticks feed primarily on medium to large mammals like white-tailed deer, raccoons, cattle, domestic pets, and people but can also be found on squirrels and birds such as sparrows and turkeys. All tick stages are commonly found on white-tailed deer.",
          habitat: "Forests and forest edges across New Jersey, with the greatest numbers in the coastal plains and the Pinelands.",
          njLocations: "This tick species has been expanding north, regaining its range before agricultural practices in the 19th century removed most New Jersey forests. Recent detections have occurred in Hunterdon and Somerset counties.",
          activeMonths: "Lone star ticks are active in New Jersey from March through October. The larvae are most abundant in the Fall and can attach to hosts as larval “balls” of hundreds of individuals - sometimes called “seed ticks.”",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1003/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1003/thumbnail.jpg",
          mapImgUrl: "",
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1003/thumbnail.jpg\", \"/images/slide22.jpeg\", \"/images/xx.jpeg\", \"/images/lone-star-occi.png\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 3,
          common: "Gulf Coast tick",
          scientific: "Amblyomma maculatum",
          humanHosts: 1,
          intro: "Historically, the Gulf Coast tick was restricted to the southeastern U.S. states. Adults of this species are aggressive human biters and they can transmit pathogens that result in tick-borne diseases, some of which affect companion animals. Established populations of this tick have just been documented in New Jersey. Understanding the distribution of this tick species in NJ is one of the objectives of the NJ Ticks 4 Science! project. ",
          hosts: "Gulf Coast ticks feed on small to large mammals and birds as well as wild and domestic mammals such as deer, cattle, and pets (dogs and cats). Adults are the life stage most likely to bite people.",
          habitat: "Open pastures, grassland environments (even mowed fields) and old fields undergoing succession to forests near wetlands. In the Northeast, many collections of Gulf Coast ticks have been in large bird sanctuaries in repurposed landfills near rivers and estuaries.",
          njLocations: "In 2013-14, established populations of Gulf Coast ticks were detected in Delaware and more recently (2021, 2022) in Connecticut, Staten Island, New York City and near Philadelphia, Pennsylvania.  In June 2022 an established population was also found in southern NJ (Salem Co.). We ask NJ residents to send us any ticks they encounter so we may pinpoint other populations of this dangerous tick species.",
          activeMonths: "In Virginia, Maryland, and Delaware, adult Gulf Coast ticks occur from May through October in the environment. Nymphs and larvae are collected rarely and usually occur in the Fall.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1011/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1011/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1011/thumbnail.jpg\", \"/images/slide3.jpeg\", \"/images/slide28.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 4,
          common: "bat tick",
          scientific: "Alectorobius kelleyi (formerly known as Carius kelleyi)",
          humanHosts: 0,
          intro: "The bat tick is a recent addition to the New Jersey tick list and is the only “soft tick” on the list! Soft ticks are in a different family than hard ticks and have slightly different features and life histories. C. kelleyi feeds primarily on big brown bats in the Northeastern United States. If given access, bat ticks will explore the living quarters, and people or pets may be a bit.  Sealing any cracks and access points to attics inhabited by bats is important.",
          hosts: "Bat ticks feed on bats, however, these ticks are opportunistic and can feed on pets and other mammals, such as humans, if bats are not present. ",
          habitat: "Bat ticks can be found in bat roosts, which may be in caves, attics, barns, or cabins. The larvae feed up to 24 hours on bats and can be detected on a bat caught outside the roost. The nymphs and adults feed briefly (up to 20 minutes) and spend their remaining time in guano (bat poop) or crevices on the roost's walls.",
          njLocations: "The first collections of bat ticks in New Jersey were from injured big brown bats brought to bat rehabilitation centers in Mercer and Sussex counties. While their distribution is unknown, given the hosts they feed on, we can assume they have a widespread distribution in the state.",
          activeMonths: "Due to the protected environment in caves and roosts, bat ticks do not have a seasonal pattern of occurrence, and all stages can occur all year round.  \nNote: Soft ticks can go for many years without a host. Since bats have different winter and summer roosts, bat ticks may be present in the absence of bats.",
          buttonImgUrl: "https://bugwoodcloud.org/images/384x256/5471220.jpg",
          "featureImgUrl": "https://bugwoodcloud.org/images/384x256/5471220.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://bugwoodcloud.org/images/384x256/5471220.jpg\", \"https://bugwoodcloud.org/images/384x256/5471221.jpg\", \"/images/Ckelleyi5656.jpg\", \"/images/slide29.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 5,
          common: "winter tick, moose tick",
          scientific: "Dermacentor albipictus",
          humanHosts: 0,
          intro: "The winter tick is a one-host tick, which means they latch onto a host as larvae, blood feed and molt into nymphs, blood feed, and then molt into adults all while remaining on the same host. Blood engorged females drop off onto the forest floor to lay eggs. The only questing life stage is the larva. Their primary hosts are moose, distributed in the U.S. between Maine, Washington, and Alaska. In New Jersey, the winter tick feeds primarily on white-tailed deer. ",
          hosts: "Moose or other ungulates such as deer, elk, caribou, and mountain sheep. In New Jersey, primary hosts are white-tailed deer.",
          habitat: "Winter ticks are found in forested areas where their hosts live.",
          njLocations: "Information on the distribution of winter ticks in New Jersey is limited. There are known records from Monmouth and Ocean counties, but given the ubiquity of white-tailed deer throughout the state, their distribution is likely more extensive.",
          activeMonths: "These ticks may be active in New Jersey from February through November.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1023/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1023/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1023/thumbnail.jpg\", \"/images/Dalbipictis2.jpg\", \"/images/slide30.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 6,
          common: "American dog tick",
          scientific: "Dermacentor variabilis",
          humanHosts: 1,
          intro: "The American dog tick is often found in fields and forest edges than in wooded/forested areas. This tick may live for up to two years without a blood host. They are traditionally considered the vectors of spotted fever group rickettsia, however recent studies (including one from Rutgers scientists- here!) failed to detect pathogenic rickettsia bacteria in New Jersey American dog ticks.",
          hosts: "American dog ticks feed on small mammals such as white-footed mice, meadow voles, rats, deer, livestock, dogs, and people.  Note: The only life stage that actively bites people are adult American dog ticks. The larvae and nymphs feed on small wild mammals that live in burrows. After feeding, engorged larvae molt into nymphs inside the burrows and feed again on the same host. Only adults venture outside looking for larger mammals such as livestock and deer.",
          habitat: "Tree-line edges with barely any tree coverage, grassy fields, meadows, and areas of tall grass bordering trails used by animals. In urban areas, American dog ticks may be present in vacant lots, utility rights-of-way, and roadsides with overgrown grass.",
          njLocations: "These ticks occur statewide.",
          activeMonths: "American dog ticks are active throughout New Jersey from March through September, with adult peak abundance occurring in April through July.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1031/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1031/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1031/thumbnail.jpg\", \"/images/D-variabilis.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 7,
          common: "rabbit tick",
          scientific: "Haemaphysalis leporispalustris",
          humanHosts: 0,
          intro: "Like the “other” rabbit tick (Ixodes dentatus), H. leporispalustris is commonly found on rabbits. This tick species rarely bite humans, thus posing a low threat to spreading tick-borne diseases. However, the rabbit tick supports the circulation of spotted fever group rickettsioses (SFGR) among wildlife, including Rocky Mountain Spotted fever, a tick-borne disease that can be deadly to humans and companion animals.",
          hosts: "The rabbit tick primarily feeds on ground-dwelling birds, rodents, and rabbits. ",
          habitat: "The rabbit tick is primarily found in meadows and fields where its hosts live.",
          njLocations: "The tick has been collected in several New Jersey counties distributed throughout the state.",
          activeMonths: "The seasonal activity of this species in New Jersey is unknown. \nNote: In California, adult and nymph life stages are collected year-round, with larvae and nymphs peaking during the late summer and into the fall season. ",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1039/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1039/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1039/thumbnail.jpg,\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1041/thumbnail.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 8,
          common: "Asian longhorned tick",
          scientific: "Haemaphysalis longicornis",
          humanHosts: 0,
          intro: "The Asian longhorned tick, a native of China, was first reported in the U.S. in New Jersey in 2017 by Center for Vector Biology at Rutgers University members. This invasive tick is cold-adapted to survive the New Jersey winters, like all the local species. Important note: the Asian longhorned tick is parthenogenetic, which means an unmated female can produce offspring that are all genetically identical to her (clones). This species can reach high infestations on cattle and other farm animals and feeds on wild mammals, birds, and occasionally on humans. It is a significant pest to dogs.",
          hosts: "Asian longhorned ticks have been collected while feeding on squirrels, rabbits, skunks, opossum, groundhogs, raccoons, dogs, and people. Despite large infestations in grassy fields in New Jersey, these ticks rarely feed on people, although, in the Fall, huge infestations of the very small larvae can produce itchy bites and have been confused with chiggers.",
          habitat: "Tall grasses, meadows, and pastures. Also ecotones and farms. Note: An ecotone is a transition between two ecological areas: forest and grassland. Man-made habitats such as a soccer field next to woods are common habitats for Asian longhorned ticks.",
          njLocations: "The first report of Asian longhorned ticks was in Hunterdon County in 2017.  Large infestations of this species have been reported in Bergen, Mercer, Middlesex, Monmouth, Somerset, & Union counties. This tick is an invasive species and a threat to the state's livestock, companion animals, and potentially people too (in Asia, this tick vectors Dabie bandavirus, a deadly virus).",
          activeMonths: "These ticks are active in New Jersey from March through October.",
          buttonImgUrl: "https://media.npr.org/assets/img/2018/02/23/longhorned-ticks_wide-cb558bd04f51bf253cf572ad76b5f330b3a903b9-s800-c85.webp",
          featureImgUrl: "/images/Asian-longhorned-egizi.png",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"/images/Asian-longhorned-egizi.png\", \"/images/Engorged-HL16.jpeg\", \"/images/HL-slide-45.jpeg\", \"/images/asian-long.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 9,
          common: "bird tick",
          scientific: "Ixodes brunneus",
          humanHosts: 0,
          intro: "Ixodes brunneus feeds primarily on passerines (songbirds), and while it has not been collected biting humans, this species is of veterinary importance. Infestations of bird ticks can cause avian tick paralysis and loss of sight (when biting near the eyes), resulting in the bird's death if not removed. In New Jersey, bird ticks have been collected from a winter wren.",
          hosts: "The primary hosts are passerines. The order Passeriformes includes primarily perching songbirds such as sparrows, finches, warblers, thrushes, tanagers, orioles, jays, chickadees, wrens, and more! There are roughly 5,000 bird species classified as passerines.",
          habitat: "The bird tick is considered rare in New Jersey. Recent surveillance in Delaware, where the species was detected for the first time in 2022, indicates the species is restricted to the Atlantic coastal plains.",
          njLocations: "The first report of this tick in New Jersey was in Cumberland County, but bird ticks are thought to have a wide distribution across the U.S.",
          activeMonths: "Bird ticks were collected from the environment in Delaware during the winter months (January to early April).",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1059/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1059/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1059/thumbnail.jpg\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1061/thumbnail.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 10,
          common: "groundhog tick (woodchuck tick)",
          scientific: "Ixodes cookei",
          humanHosts: 0,
          intro: "The groundhog tick is distributed across the eastern and central U.S. Its preferred hosts are groundhogs. This tick species may transmit the Powassan virus, an emerging tick-borne disease. The variant of Powassan virus it carries (POWV) is different from the Powassan variant carried by the blacklegged tick, which is called “deer-tick virus” (DTV). To view specific differences between groundhog ticks and blacklegged ticks, visit the website of the Institut National de Santé Publique du Québec on Ixodes cookei.",
          hosts: "As the common name indicates, the preferred hosts of these ticks are groundhogs (woodchucks), although this tick species can also be found on other small-to-medium mammals such as raccoons, foxes, skunks, rodents, and pets. The groundhog tick rarely bites people but is considered a zoonotic vector of the Powassan virus (POWV), an emerging public health threat. ",
          habitat: "Groundhog ticks thrive in forests, hedgerows, and pastures where their hosts are common. ",
          njLocations: "Groundhog ticks were first reported in New Jersey in Bergen County and were identified in Burlington County, New Jersey, in recent years. It is likely to be present across the state associated with groundhog populations.",
          activeMonths: "These ticks are primarily associated with groundhogs and often remain inside their burrows. However, in nearby New York, different life stages were found questing in May (adults and larvae) and November (nymphs).",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1063/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1063/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1063/thumbnail.jpg\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1065/thumbnail.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 11,
          common: "rabbit tick",
          scientific: "Ixodes dentatus",
          humanHosts: 0,
          intro: "Like the “other” rabbit tick (Haemaphysalis leporispalustris), I. dentatus feeds on rabbits, small to medium-sized mammals, and songbirds. There are limited national records of this tick species, which may be an important zoonotic vector of the Lyme bacterium Borrelia burgdorferi.",
          hosts: "In New Jersey, this tick species has been predominantly collected from eastern cotton-tailed rabbits, and there are no records of it biting humans.",
          habitat: "Grasslands, brushy woodlands, and croplands.",
          njLocations: "Detections in New Jersey have been spotty (Ocean County, Bergen County, Union County), but this tick species is likely widespread across New Jersey. ",
          activeMonths: "This tick may have an active period in New Jersey from May through November.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1067/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1067/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1067/thumbnail.jpg\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1069/thumbnail.jpg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 12,
          common: "raccoon tick",
          scientific: "Ixodes texanus",
          humanHosts: 0,
          intro: "The raccoon tick does not usually bite humans. However, they can reach high numbers on raccoons and other ectoparasites such as bedbugs, fleas, mites, and other ticks. It is generally best to avoid raccoons and let a trained wildlife professional handle them.",
          hosts: "In New Jersey, the preferred host for these ticks is raccoons. In other states, raccoon ticks have been found feeding on other carnivorous mammals such as weasels and badgers.",
          habitat: "Moist woodland areas, farmlands, suburban and urban areas.",
          njLocations: "Detections of raccoon ticks in New Jersey have been spotty (Burlington County and, more recently, Union County), but this tick species is likely widespread across New Jersey.",
          activeMonths: "Based on the known activity of raccoons, these ticks may be active in New Jersey from January through July.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1095/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1095/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1095/thumbnail.jpg\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1097/preview.jpg\", \"/images/slide35.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 13,
          common: "brown dog tick",
          scientific: "Rhicephalus sanguineus",
          humanHosts: 0,
          intro: "The brown dog tick is an invasive tick that primarily feeds on domestic dogs. Originally from Africa, it now has a worldwide distribution, although, in cooler climates like New Jersey, they are most common in kennels, shelters, or other pet care facilities. Of note, dogs can bring brown dog ticks with them, causing an infestation in private homes. Always check dogs for ticks after housing them.",
          hosts: "As the name indicates, the brown dog tick feeds primarily on domestic dogs and is the only hard tick in New Jersey able to survive indoors. Other tick species are most often killed by the dry air created by indoor heating and cooling systems.",
          habitat: "In New Jersey, the brown dog tick is most likely to be found in kennels, so careful vetting of kennels and inspection of dogs after boarding is necessary.",
          njLocations: "The first report in New Jersey was in Atlantic County, but brown dog ticks likely occur statewide.",
          activeMonths: "Brown dog ticks can be active all year round when living inside. They feed on dogs primarily on the head, ears, back, toes, and between joints. Once they finish blood feeding, this tick species will drop from its host and find a crevice in a sofa or wall to molt to the next stage (or lay eggs in the case of the female). This can potentially create an infestation in a kennel or home.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1101/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1101/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1101/thumbnail.jpg\", \"https://www.cdc.gov/ticks/images/gallery/Rhipicephalussanguineus_hires-small.jpg?_=42194?noicon\", \"/images/slide36.jpeg\"]}",
          createdAt: "2022-04-20 13:17:24",
          updatedAt: "2022-04-20 13:17:24",
          deletedAt: null
      },
      {
          id: 14,
          common: "squirrel tick",
          scientific: "Ixodes marxi",
          humanHosts: 0,
          intro: "The squirrel tick is considered an enzootic vector of the Powassan virus (POWV), a deadly pathogen to humans. Enzootic vectors transmit pathogens among wildlife species facilitating the infection of more ticks.",
          hosts: "While the primary hosts of the squirrel tick are squirrels, ticks of this species have been found on other small or medium-sized mammals such as rodents, raccoons, and rabbits. The squirrel tick rarely bites people.",
          habitat: "This tick can be found in the nests or feeding on squirrels, their primary hosts, and is distributed mainly in the Northeast region of the U.S. ",
          njLocations: "The first confirmed and vouchered report of a squirrel tick in New Jersey was in 2021 during surveillance of mammals in the Rutgers University-New Brunswick, Cook campus.",
          activeMonths: "Squirrels nest twice a year in NJ: from December to February and from late June through August, which may be when squirrel ticks are primarily active in the environment.",
          buttonImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1075/thumbnail.jpg",
          featureImgUrl: "https://digitalcommons.georgiasouthern.edu/usntc_key/1075/thumbnail.jpg",
          mapImgUrl: null,
          refImgArray: "{\"images\": [\"https://digitalcommons.georgiasouthern.edu/usntc_key/1075/thumbnail.jpg\", \"https://digitalcommons.georgiasouthern.edu/usntc_key/1077/thumbnail.jpg\"]}",
          createdAt: "2022-04-28 18:54:20",
          updatedAt: "2022-04-28 18:54:20",
          deletedAt: null
      }
  ], {});
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('ticks', null, {});
  }
};
